const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');
const context={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('supabase/functions/verify-google-purchase/entitlement.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,context);
const {entitlementFromGoogle:check,assertPurchaseOwner:owner}=context.exports;
const now=Date.parse('2026-09-19T12:00:00Z');
const purchase=(state,expiry='2026-10-19T12:00:00Z')=>({subscriptionState:state,lineItems:[{productId:'swift_invoice_pro_monthly',expiryTime:expiry}]});
for(const state of ['ACTIVE','IN_GRACE_PERIOD','CANCELED']) assert.equal(check(purchase('SUBSCRIPTION_STATE_'+state),now).active,true);
for(const state of ['ON_HOLD','PAUSED','EXPIRED']) assert.equal(check(purchase('SUBSCRIPTION_STATE_'+state),now).active,false);
assert.equal(check(purchase('SUBSCRIPTION_STATE_ACTIVE','2026-09-19T12:00:00Z'),now).active,false);
assert.equal(check(purchase('SUBSCRIPTION_STATE_CANCELED','2026-09-18T12:00:00Z'),now).active,false);
assert.equal(check(purchase('SUBSCRIPTION_STATE_ACTIVE'),now).expiresAt,'2026-10-19T12:00:00.000Z');
for(const state of ['PENDING','PENDING_PURCHASE_CANCELED','UNSPECIFIED'])assert.throws(()=>check(purchase('SUBSCRIPTION_STATE_'+state),now));
assert.throws(()=>check({subscriptionState:'SUBSCRIPTION_STATE_ACTIVE',lineItems:[{productId:'unrelated',expiryTime:'2099-01-01'}]},now));
assert.throws(()=>check(purchase('SUBSCRIPTION_STATE_ACTIVE','invalid'),now));
owner({externalAccountIdentifiers:{obfuscatedExternalAccountId:'hash-a'}},'hash-a',null,'user-a');
owner({},'hash-a','user-a','user-a');
assert.throws(()=>owner({},'hash-a',null,'user-a'));
assert.throws(()=>owner({},'hash-a','user-b','user-a'));
assert.throws(()=>owner({externalAccountIdentifiers:{obfuscatedExternalAccountId:'hash-b'}},'hash-a','user-a','user-a'));
console.log('Google entitlement: active/grace/cancelled/expired/held/pending states, exact expiry, products and account binding passed.');
