const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const vm = require('node:vm');
const source = fs.readFileSync('src/utils/invoiceValues.ts', 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const context = { exports: {} };
vm.runInNewContext(compiled, context);
const { calendarDate, parseDisplayDate, positiveNumber, paymentTerms, isOutstanding } = context.exports;
process.env.TZ = 'America/New_York';
assert.equal(calendarDate(parseDisplayDate('2026-09-01')), '2026-09-01');
assert.equal(parseDisplayDate('2026-09-01').getMonth(), 8);
assert.equal(parseDisplayDate('2026-03-08').getDate(), 8);
for (const value of ['', '0', '-1', 'NaN', 'Infinity', '1abc']) assert.equal(positiveNumber(value), null);
assert.equal(positiveNumber('1.5'), 1.5);
assert.equal(paymentTerms('0'), 0);
assert.equal(paymentTerms('30'), 30);
for (const value of ['', '-1', '1.5', 'Infinity', '3660']) assert.equal(paymentTerms(value), null);
assert.equal(isOutstanding('draft'), false);
assert.equal(isOutstanding('cancelled'), false);
assert.equal(isOutstanding('sent'), true);
assert.equal(isOutstanding('overdue'), true);
console.log('Invoice date, numeric input, terms, and outstanding-status regressions passed.');
